### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/website#19]
Hola @Enchufa2:

Parece que el sitio web no está funcionando: https://ropenspain.es/

Supongo que ya se habrá realizado el cambio que @cjgb comentó en el Slack. Comentamos para ver cómo arreglarlo

PS: Si quieres podemos verlo por Slack también

**Comment by Enchufa2** [comment]
La redirección DNS la debí configurar mal con las prisas. Lo miro esta tarde después de clase.

**Comment by Enchufa2** [comment]
Parece que ahora sí se está propagando. Tardará varias horas probablemente en estar fully available. Se puede tener una idea del progreso [aquí](https://www.whatsmydns.net/#A/ropenspain.es).
